### ISSUE TITLE
"ionic platform" changed to "ionic cordoba platform"

### ISSUE THREAD

**Issue by joaocc** [spheras/backingtrainer#3]
Happened when trying to build using ionic-3.4.0 on mac osx

**Comment by spheras** [comment]
Hi @joaocc , did you achieve to compile it for mac?  I don't have experience with IOS/mac and it could be great to have a version compiled for those users.  My intention is to close the first version during these weeks and generate (and share) the binary versions (windows/linux/mac/android/ and ios if possible).

**Comment by joaocc** [comment]
The steps didn't work on Mac. Unfortunately I will not have time to try to fix it. I was just trying it out. Thx
